---
- name: Chocolatey Facts and Configuration
  hosts: all
  gather_facts: false
  tasks:

  - name: Gather facts from Chocolatey
    chocolatey.chocolatey.win_chocolatey_facts:

  - name: Displays the gathered facts
    ansible.builtin.debug:
      var: ansible_chocolatey

  - name: Create a directory for the new Chocolatey caching directory
    ansible.windows.win_file:
      path: C:\ChocoCache
      state: directory

  - name: Configure Chocolatey to use the new directory as the cache location
    chocolatey.chocolatey.win_chocolatey_config:
      name: cacheLocation
      state: present
      value: C:\ChocoCache

  - name: Change the Execution Timeout Setting
    chocolatey.chocolatey.win_chocolatey_config:
      name: commandExecutionTimeoutSeconds
      state: present
      value: 3600

  - name: ReGather facts from Chocolatey after new reconfiguring
    chocolatey.chocolatey.win_chocolatey_facts:

  - name: Displays the gathered facts
    ansible.builtin.debug:
      var: ansible_chocolatey.config
